baseurl = "https://mjyi.github.io/"
title = "Blank's Blog"
languageCode = "en-us"
disqusShortname = "mjyi-io"
copyright = "Copyright (c) 2015 - 2017, blanK; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "blanK"

[indexes]
    tag = "tags"
    topic = "topics"

